// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nagp.eBroker.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using System.Diagnostics.CodeAnalysis;

namespace Nagp.eBroker.Migrations
{
    [DbContext(typeof(EBrokerContext))]
    [ExcludeFromCodeCoverage]
    partial class EBrokerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Nagp.eBroker.Data.Entities.BrokerAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("AccountName")
                        .HasColumnType("integer");

                    b.Property<decimal>("Funds")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("BrokerAccounts");
                });

            modelBuilder.Entity("Nagp.eBroker.Data.Entities.EquitieHold", b =>
                {
                    b.Property<int>("BrokerAccountId")
                        .HasColumnType("integer");

                    b.Property<int>("EquityId")
                        .HasColumnType("integer");

                    b.Property<int>("HoldUnits")
                        .HasColumnType("integer");

                    b.HasKey("BrokerAccountId", "EquityId");

                    b.HasIndex("EquityId");

                    b.ToTable("EquitieHolds");
                });

            modelBuilder.Entity("Nagp.eBroker.Data.Entities.Equity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<double>("PricePerUnit")
                        .HasColumnType("double precision");

                    b.Property<int>("Units")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Equities");
                });

            modelBuilder.Entity("Nagp.eBroker.Data.Entities.EquitieHold", b =>
                {
                    b.HasOne("Nagp.eBroker.Data.Entities.BrokerAccount", "BrokerAccount")
                        .WithMany("EquitieHolds")
                        .HasForeignKey("BrokerAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nagp.eBroker.Data.Entities.Equity", "Equity")
                        .WithMany()
                        .HasForeignKey("EquityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BrokerAccount");

                    b.Navigation("Equity");
                });

            modelBuilder.Entity("Nagp.eBroker.Data.Entities.BrokerAccount", b =>
                {
                    b.Navigation("EquitieHolds");
                });
#pragma warning restore 612, 618
        }
    }
}
